name: learn
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: any
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.3
  flutter_custom_clippers: ^2.1.0
  flutter_screenutil: ^5.8.4
  flutter_scripts: ^0.0.3
  font_awesome_flutter: ^10.5.0
  get_it: ^7.6.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.1.4
  meta: ^1.9.1
  # nb_utils: ^6.0.2
  progress_state_button: ^1.0.4
  retrofit: ^3.0.1+1
  wave: ^0.2.2
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  nb_utils: ^6.0.3

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  retrofit_generator: null

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs

  assets:
    - assets/icons/
    - assets/images/
    - assets/voice/
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
